name: Publish to PyPI
on:
  release:
    types: [published]

jobs:
  pypi_release:
    env:
      PYTHON_KEYRING_BACKEND: "keyring.backends.null.Keyring"
    name: Builds Using Poetry and Publishes to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.2.2
          poetry install
        
      - name: Configure poetry
        run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
      - name: Publish package
        run: poetry publish --build
